export const countries = [
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Australia", label: "Australia" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Brunei", label: "Brunei" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "China", label: "China" },
  { value: "Fiji", label: "Fiji" },
  { value: "India", label: "India" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Japan", label: "Japan" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Laos", label: "Laos" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Maldives", label: "Maldives" },
  { value: "Marshall Islands", label: "Marshall Islands" },
  { value: "Micronesia", label: "Micronesia" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Nauru", label: "Nauru" },
  { value: "Nepal", label: "Nepal" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "North Korea", label: "North Korea" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Palau", label: "Palau" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Philippines", label: "Philippines" },
  { value: "Samoa", label: "Samoa" },
  { value: "Singapore", label: "Singapore" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "South Korea", label: "South Korea" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Thailand", label: "Thailand" },
  { value: "Timor-Leste", label: "Timor-Leste" },
  { value: "Tonga", label: "Tonga" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Vanuatu", label: "Vanuatu" },
  { value: "Vietnam", label: "Vietnam" },
];
